-- DB_Schema.sql
-- Airline Management System - Oracle SQL Schema

-- ========================
-- USER TABLES
-- ========================

CREATE TABLE ADMIN (
    USERID      NUMBER PRIMARY KEY,
    CNIC        VARCHAR2(16) UNIQUE NOT NULL,
    NAME        VARCHAR2(35) NOT NULL,
    PHONE_NO    VARCHAR2(13) UNIQUE NOT NULL,
    PASSWORD    VARCHAR2(30) NOT NULL,
    EMAIL       VARCHAR2(30) UNIQUE NOT NULL
);

CREATE TABLE PASSENGER (
    USERID      NUMBER PRIMARY KEY,
    CNIC        VARCHAR2(16) UNIQUE NOT NULL,
    NAME        VARCHAR2(35) NOT NULL,
    PHONE_NO    VARCHAR2(13) UNIQUE NOT NULL,
    PASSWORD    VARCHAR2(30) NOT NULL,
    EMAIL       VARCHAR2(30) UNIQUE NOT NULL
);

CREATE TABLE EMPLOYEE (
    USERID      NUMBER PRIMARY KEY,
    CNIC        VARCHAR2(16) UNIQUE NOT NULL,
    NAME        VARCHAR2(35) NOT NULL,
    PHONE_NO    VARCHAR2(13) UNIQUE NOT NULL,
    PASSWORD    VARCHAR2(30) NOT NULL,
    EMAIL       VARCHAR2(30) UNIQUE NOT NULL
);

-- ========================
-- FLIGHT & AIRCRAFT
-- ========================

CREATE TABLE AIRCRAFT (
    AIRCRAFT_ID NUMBER PRIMARY KEY,
    MODEL       VARCHAR2(30),
    SEATS       NUMBER NOT NULL
);

CREATE TABLE FLIGHT (
    FLIGHT_ID           NUMBER PRIMARY KEY,
    DESTINATION         VARCHAR2(30) NOT NULL,
    DEPARTURE_LOCATION  VARCHAR2(30) NOT NULL,
    ARRIVAL_TIME        TIMESTAMP NOT NULL,
    DEPARTURE_TIME      TIMESTAMP NOT NULL,
    STATUS              VARCHAR2(15) NOT NULL,
    AIRCRAFT_ID         NUMBER NOT NULL,
    AV_SEATS            NUMBER NOT NULL,
    FOREIGN KEY (AIRCRAFT_ID) REFERENCES AIRCRAFT(AIRCRAFT_ID)
);

-- ========================
-- BOOKING SYSTEM
-- ========================

CREATE TABLE BOOKING (
    BOOKING_ID      NUMBER PRIMARY KEY,
    PASSENGER_ID    NUMBER NOT NULL,
    FLIGHT_ID       NUMBER NOT NULL,
    COST            NUMBER NOT NULL,
    SEAT_NO         NUMBER NOT NULL,
    STATUS          VARCHAR2(10),
    TICKET          VARCHAR2(10),
    FOREIGN KEY (PASSENGER_ID) REFERENCES PASSENGER(USERID),
    FOREIGN KEY (FLIGHT_ID) REFERENCES FLIGHT(FLIGHT_ID)
);

-- ========================
-- FINANCIAL & FEEDBACK
-- ========================

CREATE TABLE REVENUE (
    REVENUE_ID         NUMBER PRIMARY KEY,
    SOURCE             NUMBER NOT NULL,
    AMMOUNT            NUMBER NOT NULL,
    TRANSACTION_DATE   TIMESTAMP NOT NULL,
    DESCRIPTION        VARCHAR2(45),
    FOREIGN KEY (SOURCE) REFERENCES BOOKING(BOOKING_ID)
);

CREATE TABLE FEEDBACK (
    PASSENGER_ID    NUMBER,
    FLIGHT_ID       NUMBER,
    FEEDBACK        VARCHAR2(50),
    FOREIGN KEY (PASSENGER_ID) REFERENCES PASSENGER(USERID),
    FOREIGN KEY (FLIGHT_ID) REFERENCES FLIGHT(FLIGHT_ID)
);

-- ========================
-- EMPLOYEE TASKS
-- ========================

CREATE TABLE TASK (
    TASK_ID         NUMBER PRIMARY KEY,
    EMP_ID          NUMBER NOT NULL,
    FLIGHT_ID       NUMBER NOT NULL,
    TASK            VARCHAR2(50),
    DATE_COMPLETED  TIMESTAMP,
    FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(USERID),
    FOREIGN KEY (FLIGHT_ID) REFERENCES FLIGHT(FLIGHT_ID)
);
